[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  name = "github.com/mdlayher/genetlink"
  branch = "master"

[[constraint]]
  name = "github.com/mdlayher/netlink"
  branch = "master"

[[constraint]]
  name = "github.com/vishvananda/netlink"
  branch = "master"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "golang.org/x/sys"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.16.0"

[[constraint]]
  name = "github.com/u-root/u-root"
  branch = "master"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[[constraint]]
  name = "github.com/fullstorydev/grpcurl"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
