// Copyright 2018 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: bmc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Button int32

const (
	Button_BUTTON_UNSPEC Button = 0
	Button_BUTTON_POWER  Button = 1
	Button_BUTTON_RESET  Button = 2
)

// Enum value maps for Button.
var (
	Button_name = map[int32]string{
		0: "BUTTON_UNSPEC",
		1: "BUTTON_POWER",
		2: "BUTTON_RESET",
	}
	Button_value = map[string]int32{
		"BUTTON_UNSPEC": 0,
		"BUTTON_POWER":  1,
		"BUTTON_RESET":  2,
	}
)

func (x Button) Enum() *Button {
	p := new(Button)
	*p = x
	return p
}

func (x Button) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Button) Descriptor() protoreflect.EnumDescriptor {
	return file_bmc_proto_enumTypes[0].Descriptor()
}

func (Button) Type() protoreflect.EnumType {
	return &file_bmc_proto_enumTypes[0]
}

func (x Button) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Button.Descriptor instead.
func (Button) EnumDescriptor() ([]byte, []int) {
	return file_bmc_proto_rawDescGZIP(), []int{0}
}

type ButtonPressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required: which button to press
	Button Button `protobuf:"varint,1,opt,name=button,proto3,enum=proto.Button" json:"button,omitempty"`
	// Required: duration in milliseconds for how long to press the button
	DurationMs uint32 `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
}

func (x *ButtonPressRequest) Reset() {
	*x = ButtonPressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bmc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ButtonPressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonPressRequest) ProtoMessage() {}

func (x *ButtonPressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bmc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonPressRequest.ProtoReflect.Descriptor instead.
func (*ButtonPressRequest) Descriptor() ([]byte, []int) {
	return file_bmc_proto_rawDescGZIP(), []int{0}
}

func (x *ButtonPressRequest) GetButton() Button {
	if x != nil {
		return x.Button
	}
	return Button_BUTTON_UNSPEC
}

func (x *ButtonPressRequest) GetDurationMs() uint32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ButtonPressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ButtonPressResponse) Reset() {
	*x = ButtonPressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bmc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ButtonPressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonPressResponse) ProtoMessage() {}

func (x *ButtonPressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bmc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonPressResponse.ProtoReflect.Descriptor instead.
func (*ButtonPressResponse) Descriptor() ([]byte, []int) {
	return file_bmc_proto_rawDescGZIP(), []int{1}
}

type GetFansRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetFansRequest) Reset() {
	*x = GetFansRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bmc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFansRequest) ProtoMessage() {}

func (x *GetFansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bmc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFansRequest.ProtoReflect.Descriptor instead.
func (*GetFansRequest) Descriptor() ([]byte, []int) {
	return file_bmc_proto_rawDescGZIP(), []int{2}
}

type Fan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fan        uint32 `protobuf:"varint,1,opt,name=fan,proto3" json:"fan,omitempty"`
	Percentage uint32 `protobuf:"varint,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Rpm        uint32 `protobuf:"varint,3,opt,name=rpm,proto3" json:"rpm,omitempty"`
}

func (x *Fan) Reset() {
	*x = Fan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bmc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fan) ProtoMessage() {}

func (x *Fan) ProtoReflect() protoreflect.Message {
	mi := &file_bmc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fan.ProtoReflect.Descriptor instead.
func (*Fan) Descriptor() ([]byte, []int) {
	return file_bmc_proto_rawDescGZIP(), []int{3}
}

func (x *Fan) GetFan() uint32 {
	if x != nil {
		return x.Fan
	}
	return 0
}

func (x *Fan) GetPercentage() uint32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *Fan) GetRpm() uint32 {
	if x != nil {
		return x.Rpm
	}
	return 0
}

type GetFansResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fan []*Fan `protobuf:"bytes,1,rep,name=fan,proto3" json:"fan,omitempty"`
}

func (x *GetFansResponse) Reset() {
	*x = GetFansResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bmc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFansResponse) ProtoMessage() {}

func (x *GetFansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bmc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFansResponse.ProtoReflect.Descriptor instead.
func (*GetFansResponse) Descriptor() ([]byte, []int) {
	return file_bmc_proto_rawDescGZIP(), []int{4}
}

func (x *GetFansResponse) GetFan() []*Fan {
	if x != nil {
		return x.Fan
	}
	return nil
}

type ConsoleData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ConsoleData) Reset() {
	*x = ConsoleData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bmc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsoleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleData) ProtoMessage() {}

func (x *ConsoleData) ProtoReflect() protoreflect.Message {
	mi := &file_bmc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleData.ProtoReflect.Descriptor instead.
func (*ConsoleData) Descriptor() ([]byte, []int) {
	return file_bmc_proto_rawDescGZIP(), []int{5}
}

func (x *ConsoleData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetVersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bmc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bmc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_bmc_proto_rawDescGZIP(), []int{6}
}

type GetVersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	GitHash string `protobuf:"bytes,2,opt,name=git_hash,json=gitHash,proto3" json:"git_hash,omitempty"`
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bmc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bmc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_bmc_proto_rawDescGZIP(), []int{7}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetVersionResponse) GetGitHash() string {
	if x != nil {
		return x.GitHash
	}
	return ""
}

var File_bmc_proto protoreflect.FileDescriptor

var file_bmc_proto_rawDesc = []byte{
	0x0a, 0x09, 0x62, 0x6d, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x12, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x50, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x06, 0x62, 0x75, 0x74, 0x74,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x52, 0x06, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x12,
	0x1f, 0x0a, 0x0b, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73,
	0x22, 0x15, 0x0a, 0x13, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x50, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x46, 0x61,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x03, 0x46, 0x61, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x66, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x66,
	0x61, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61,
	0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x70, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x72, 0x70, 0x6d, 0x22, 0x2f, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x61, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x03, 0x66, 0x61, 0x6e, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x61, 0x6e,
	0x52, 0x03, 0x66, 0x61, 0x6e, 0x22, 0x21, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x49, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a,
	0x08, 0x67, 0x69, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x67, 0x69, 0x74, 0x48, 0x61, 0x73, 0x68, 0x2a, 0x3f, 0x0a, 0x06, 0x42, 0x75, 0x74, 0x74,
	0x6f, 0x6e, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x55, 0x54, 0x54, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x55, 0x54, 0x54, 0x4f, 0x4e, 0x5f,
	0x50, 0x4f, 0x57, 0x45, 0x52, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x55, 0x54, 0x54, 0x4f,
	0x4e, 0x5f, 0x52, 0x45, 0x53, 0x45, 0x54, 0x10, 0x02, 0x32, 0x9b, 0x02, 0x0a, 0x11, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x46, 0x0a, 0x0b, 0x50, 0x72, 0x65, 0x73, 0x73, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x12, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x50, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x50, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x46, 0x61,
	0x6e, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x61,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x28, 0x01,
	0x30, 0x01, 0x12, 0x43, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x2d, 0x72, 0x6f, 0x6f, 0x74, 0x2f, 0x75, 0x2d, 0x62,
	0x6d, 0x63, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bmc_proto_rawDescOnce sync.Once
	file_bmc_proto_rawDescData = file_bmc_proto_rawDesc
)

func file_bmc_proto_rawDescGZIP() []byte {
	file_bmc_proto_rawDescOnce.Do(func() {
		file_bmc_proto_rawDescData = protoimpl.X.CompressGZIP(file_bmc_proto_rawDescData)
	})
	return file_bmc_proto_rawDescData
}

var file_bmc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bmc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_bmc_proto_goTypes = []interface{}{
	(Button)(0),                 // 0: proto.Button
	(*ButtonPressRequest)(nil),  // 1: proto.ButtonPressRequest
	(*ButtonPressResponse)(nil), // 2: proto.ButtonPressResponse
	(*GetFansRequest)(nil),      // 3: proto.GetFansRequest
	(*Fan)(nil),                 // 4: proto.Fan
	(*GetFansResponse)(nil),     // 5: proto.GetFansResponse
	(*ConsoleData)(nil),         // 6: proto.ConsoleData
	(*GetVersionRequest)(nil),   // 7: proto.GetVersionRequest
	(*GetVersionResponse)(nil),  // 8: proto.GetVersionResponse
}
var file_bmc_proto_depIdxs = []int32{
	0, // 0: proto.ButtonPressRequest.button:type_name -> proto.Button
	4, // 1: proto.GetFansResponse.fan:type_name -> proto.Fan
	1, // 2: proto.ManagementService.PressButton:input_type -> proto.ButtonPressRequest
	3, // 3: proto.ManagementService.GetFans:input_type -> proto.GetFansRequest
	6, // 4: proto.ManagementService.StreamConsole:input_type -> proto.ConsoleData
	7, // 5: proto.ManagementService.GetVersion:input_type -> proto.GetVersionRequest
	2, // 6: proto.ManagementService.PressButton:output_type -> proto.ButtonPressResponse
	5, // 7: proto.ManagementService.GetFans:output_type -> proto.GetFansResponse
	6, // 8: proto.ManagementService.StreamConsole:output_type -> proto.ConsoleData
	8, // 9: proto.ManagementService.GetVersion:output_type -> proto.GetVersionResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bmc_proto_init() }
func file_bmc_proto_init() {
	if File_bmc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bmc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ButtonPressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bmc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ButtonPressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bmc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFansRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bmc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bmc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFansResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bmc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsoleData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bmc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bmc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVersionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bmc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bmc_proto_goTypes,
		DependencyIndexes: file_bmc_proto_depIdxs,
		EnumInfos:         file_bmc_proto_enumTypes,
		MessageInfos:      file_bmc_proto_msgTypes,
	}.Build()
	File_bmc_proto = out.File
	file_bmc_proto_rawDesc = nil
	file_bmc_proto_goTypes = nil
	file_bmc_proto_depIdxs = nil
}
