// Code generated via go generate; DO NOT EDIT.
// This file was generated by generate.go

package config

var (
	termsAgreed    = false
	debugSSH       = false
	gitVersion     = ``
	gitHash        = ``
	simPebbleAPICA = ``
	authorizedKeys = []string{}
)
