#!/bin/bash
# Copyright 2019 the u-root Authors. All rights reserved
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

cat << _EOF_
// AUTOGENERATED BY sim_pebble.sh
package config

var (
	simPebbleAPICA = \`
$(<sim-pebble.crt)
\`
)
_EOF_
