#!/bin/bash
# Copyright 2018 the u-root Authors. All rights reserved
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

GIT_HASH_LONG=$(git rev-parse HEAD)
GIT_VERSION=$(git describe --tags --long)
cat << _EOF_
// AUTOGENERATED BY version.sh
package config

var (
	gitHash    = "${GIT_HASH_LONG}"
	gitVersion = "${GIT_VERSION}"
)
_EOF_
