// Copyright 2021 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	_ "embed"
	"log"
	"os"
	"strings"
	"text/template"
)

var (
	gitVersion = `"0"`
	gitHash    = `"none"`

	//go:embed sim-pebble.crt
	simPebbleAPICA string

	//go:embed ssh-pubkeys
	keyFile string

	genTemplate = template.Must(template.New("").Parse(`// Code generated via go generate; DO NOT EDIT.
// This file was generated by generate.go

package config

var (
	termsAgreed    = {{.Terms}}
	debugSSH       = {{.DebugSSH}}
	gitVersion     = {{.Version}}
	gitHash        = {{.Hash}}
	simPebbleAPICA = {{.APICA}}
	authorizedKeys = []string{
	{{- range .Keys}}
		{{printf "%q" .}},
	{{- end}}
	}
)
`))
)

func main() {
	authorizedKeys := strings.Split(keyFile, "\n")

	f, err := os.Create("../generated.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	genTemplate.Execute(f, struct {
		Version  string
		Hash     string
		Terms    bool
		DebugSSH bool
		APICA    string
		Keys     []string
	}{
		Version:  "`" + gitVersion + "`",
		Hash:     "`" + gitHash + "`",
		Terms:    termsAgreed,
		DebugSSH: debugSSH,
		APICA:    "`" + simPebbleAPICA + "`",
		Keys:     authorizedKeys,
	})
}
