#!/bin/bash
# Copyright 2019 u-root Authors
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file

set -eou pipefail

cd $(dirname $0)

CDIR=$(/sbin/apparmor_parser -L .app.cache -W --print-cache-dir)
/sbin/apparmor_parser -Q -I . --base . -r "${1}" -L .app.cache -W

gofmt -s << _EOF_
// AUTOGENERATED BY compile.sh '${1}'

package apparmor

func init() {
  profiles = append(profiles, []byte{
$(xxd -i "${CDIR}/${1}" | head -n-2 | tail -n+2),
})
}
_EOF_

rm -fr .app.cache


