// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package bmc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Route struct {
	// Destination network
	// Example: 192.168.0.100/24
	Destination          string   `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Via                  string   `protobuf:"bytes,2,opt,name=via,proto3" json:"via,omitempty"`
	Interface            string   `protobuf:"bytes,3,opt,name=interface,proto3" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}
func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Route) GetVia() string {
	if m != nil {
		return m.Via
	}
	return ""
}

func (m *Route) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

type Network struct {
	// System's fully qualified hostname
	// Example: rack01server02.mycompany.org
	// Default: Get hostname from DHCPv4 or reverse DNS lookup
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// VLAN ID to tag traffic with
	// Default: all traffic is untagged
	Vlan uint32 `protobuf:"varint,2,opt,name=vlan,proto3" json:"vlan,omitempty"`
	// Static IPv4 address to set
	// Example: 192.168.0.100/24
	// Default: Use DHCPv4 addresses
	Ipv4Address string `protobuf:"bytes,3,opt,name=ipv4_address,json=ipv4Address,proto3" json:"ipv4_address,omitempty"`
	// Static IPv6 address to set
	// Example: fec0::100/64
	// Default: Use DHCPv6 address
	Ipv6Address string `protobuf:"bytes,4,opt,name=ipv6_address,json=ipv6Address,proto3" json:"ipv6_address,omitempty"`
	// Static IPv4 routes
	// Default: No static IPv4 routes
	Ipv4Route []*Route `protobuf:"bytes,5,rep,name=ipv4_route,json=ipv4Route,proto3" json:"ipv4_route,omitempty"`
	// Static IPv6 routes
	// Default: No static IPv6 routes
	Ipv6Route            []*Route `protobuf:"bytes,6,rep,name=ipv6_route,json=ipv6Route,proto3" json:"ipv6_route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Network) Reset()         { *m = Network{} }
func (m *Network) String() string { return proto.CompactTextString(m) }
func (*Network) ProtoMessage()    {}
func (*Network) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}
func (m *Network) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Network.Unmarshal(m, b)
}
func (m *Network) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Network.Marshal(b, m, deterministic)
}
func (m *Network) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Network.Merge(m, src)
}
func (m *Network) XXX_Size() int {
	return xxx_messageInfo_Network.Size(m)
}
func (m *Network) XXX_DiscardUnknown() {
	xxx_messageInfo_Network.DiscardUnknown(m)
}

var xxx_messageInfo_Network proto.InternalMessageInfo

func (m *Network) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Network) GetVlan() uint32 {
	if m != nil {
		return m.Vlan
	}
	return 0
}

func (m *Network) GetIpv4Address() string {
	if m != nil {
		return m.Ipv4Address
	}
	return ""
}

func (m *Network) GetIpv6Address() string {
	if m != nil {
		return m.Ipv6Address
	}
	return ""
}

func (m *Network) GetIpv4Route() []*Route {
	if m != nil {
		return m.Ipv4Route
	}
	return nil
}

func (m *Network) GetIpv6Route() []*Route {
	if m != nil {
		return m.Ipv6Route
	}
	return nil
}

type SystemConfig struct {
	Network              *Network `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemConfig) Reset()         { *m = SystemConfig{} }
func (m *SystemConfig) String() string { return proto.CompactTextString(m) }
func (*SystemConfig) ProtoMessage()    {}
func (*SystemConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{2}
}
func (m *SystemConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemConfig.Unmarshal(m, b)
}
func (m *SystemConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemConfig.Marshal(b, m, deterministic)
}
func (m *SystemConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemConfig.Merge(m, src)
}
func (m *SystemConfig) XXX_Size() int {
	return xxx_messageInfo_SystemConfig.Size(m)
}
func (m *SystemConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SystemConfig proto.InternalMessageInfo

func (m *SystemConfig) GetNetwork() *Network {
	if m != nil {
		return m.Network
	}
	return nil
}

func init() {
	proto.RegisterType((*Route)(nil), "bmc.Route")
	proto.RegisterType((*Network)(nil), "bmc.Network")
	proto.RegisterType((*SystemConfig)(nil), "bmc.SystemConfig")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0x15, 0xd2, 0x0f, 0x72, 0x09, 0x12, 0xba, 0x29, 0x42, 0x0c, 0x21, 0x03, 0x2a, 0x4b,
	0x86, 0x82, 0xbc, 0x23, 0x76, 0x06, 0x33, 0x31, 0x21, 0x27, 0x71, 0xc1, 0x82, 0xd8, 0x95, 0x6d,
	0x82, 0xf8, 0xa1, 0xfc, 0x1f, 0x94, 0xb3, 0x1b, 0x18, 0xba, 0x9d, 0xdf, 0x7b, 0xfc, 0x4a, 0xcf,
	0x41, 0xd1, 0x19, 0xbd, 0x53, 0xaf, 0xcd, 0xde, 0x1a, 0x6f, 0x30, 0x6d, 0x87, 0xae, 0x7e, 0x86,
	0x25, 0x37, 0x9f, 0x5e, 0x62, 0x05, 0x79, 0x2f, 0x9d, 0x57, 0x5a, 0x78, 0x65, 0x74, 0x99, 0x54,
	0xc9, 0x26, 0xe3, 0xff, 0x23, 0x3c, 0x87, 0x74, 0x54, 0xa2, 0x3c, 0xa1, 0xcd, 0x34, 0xe2, 0x25,
	0x64, 0x4a, 0x7b, 0x69, 0x77, 0xa2, 0x93, 0x65, 0x4a, 0xf9, 0x5f, 0x50, 0xff, 0x24, 0xb0, 0x7e,
	0x94, 0xfe, 0xcb, 0xd8, 0x77, 0xbc, 0x80, 0xd3, 0x37, 0xe3, 0xbc, 0x16, 0x83, 0x8c, 0xd5, 0xf3,
	0x1b, 0x11, 0x16, 0xe3, 0x87, 0xd0, 0x54, 0x7c, 0xc6, 0x69, 0xc6, 0x2b, 0x28, 0xd4, 0x7e, 0xbc,
	0x7b, 0x11, 0x7d, 0x6f, 0xa5, 0x73, 0xb1, 0x3c, 0x9f, 0xb2, 0xfb, 0x10, 0x45, 0x84, 0xcd, 0xc8,
	0x62, 0x46, 0xd8, 0x01, 0xb9, 0x01, 0xa0, 0x16, 0x3b, 0x19, 0x96, 0xcb, 0x2a, 0xdd, 0xe4, 0x5b,
	0x68, 0xda, 0xa1, 0x6b, 0xc8, 0x99, 0x67, 0xd3, 0x36, 0xe8, 0x07, 0x94, 0x45, 0x74, 0x75, 0x14,
	0x65, 0x34, 0xd6, 0x0c, 0x8a, 0xa7, 0x6f, 0xe7, 0xe5, 0xf0, 0x40, 0xd7, 0xc4, 0x6b, 0x58, 0xeb,
	0xa0, 0x49, 0x6a, 0xf9, 0xb6, 0xa0, 0x7f, 0x51, 0x9d, 0x1f, 0x96, 0xed, 0x8a, 0xce, 0x7e, 0xfb,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0x94, 0x56, 0x97, 0x7d, 0x86, 0x01, 0x00, 0x00,
}
