// Copyright 2018 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package bmc

import (
	"bytes"
	"crypto/ecdsa"
	"crypto/elliptic"
	crand "crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"encoding/binary"
	"encoding/pem"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"math/rand"
	"os"
	"os/exec"
	"os/signal"
	"strings"
	"time"

	"github.com/golang/protobuf/proto"
	"github.com/jpillora/backoff"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/u-root/u-bmc/config"
	"github.com/u-root/u-bmc/pkg/bmc/cert"
	"github.com/u-root/u-bmc/pkg/bmc/ttime"
	pb "github.com/u-root/u-bmc/proto"
	"github.com/u-root/u-root/pkg/rtc"
	"golang.org/x/sys/unix"
)

const banner = `
██╗   ██╗      ██████╗ ███╗   ███╗ ██████╗
██║   ██║      ██╔══██╗████╗ ████║██╔════╝
██║   ██║█████╗██████╔╝██╔████╔██║██║
██║   ██║╚════╝██╔══██╗██║╚██╔╝██║██║
╚██████╔╝      ██████╔╝██║ ╚═╝ ██║╚██████╗
 ╚═════╝       ╚═════╝ ╚═╝     ╚═╝ ╚═════╝
 `

var (
	environ       []string
	systemVersion = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: "ubmc",
		Subsystem: "system",
		Name:      "version",
		Help:      "u-bmc version metric",
	}, []string{"version"})
	systemHasTime = prometheus.NewGauge(prometheus.GaugeOpts{
		Namespace: "ubmc",
		Subsystem: "system",
		Name:      "has_trusted_time",
		Help:      "u-bmc has acquired trusted time",
	})

	timeRetry   = &backoff.Backoff{Min: 1 * time.Second, Max: 1 * time.Hour, Factor: 5, Jitter: true}
	timeRefresh = &backoff.Backoff{Min: 3 * time.Hour, Max: 6 * time.Hour, Factor: 2, Jitter: true}
	certRetry   = &backoff.Backoff{Min: 1 * time.Second, Max: 1 * time.Hour, Factor: 5, Jitter: true}
	certRefresh = &backoff.Backoff{Min: 240 * time.Hour, Max: 480 * time.Hour, Factor: 2, Jitter: true}
)

func init() {
	environ = append(os.Environ(), "USER=root")
	environ = append(environ, "HOME=/root")
	environ = append(environ, "TZ=UTC")

	prometheus.MustRegister(systemVersion)
	prometheus.MustRegister(systemHasTime)
}

type Platform interface {
	InitializeSystem() error
	HostUart() (string, int)
	GpioPlatform
	FanPlatform
}

type RPCServer interface {
	EnableRemote(*tls.Certificate) error
}

func newSshKey() []byte {
	pk, err := ecdsa.GenerateKey(elliptic.P521(), crand.Reader)
	if err != nil {
		panic(err)
	}

	asn1, err := x509.MarshalECPrivateKey(pk)
	if err != nil {
		panic(err)
	}
	return pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: asn1})
}

func createFile(file string, mode os.FileMode, c []byte) error {
	f, err := os.OpenFile(file, os.O_RDWR|os.O_CREATE, mode)
	if err != nil {
		return fmt.Errorf("open %s for write failed: %v", file, err)
	}
	defer f.Close()
	if _, err := f.Write(c); err != nil {
		return fmt.Errorf("write %s failed: %v", file, err)
	}
	return nil
}

func intrHandler(cmd *exec.Cmd, exited chan bool) {
	for {
		c := make(chan os.Signal, 1)
		signal.Notify(c, os.Interrupt)
		select {
		case _ = <-c:
			cmd.Process.Signal(os.Interrupt)
		case _ = <-exited:
			return
		}
	}
}

func startSsh(ak []string) error {
	if _, err := os.Stat("/config/ssh_host_ecdsa_key"); os.IsNotExist(err) {
		log.Printf("Generating new SSH server key")
		err := createFile("/config/ssh_host_ecdsa_key", 0400, newSshKey())
		if err != nil {
			return fmt.Errorf("createFile for ssh key: %v", err)
		}
	}
	// The variable authorizedKeys is generated by Makefiles
	createFile("/config/authorized_keys", 0600, []byte(strings.Join(ak, "\n")))
	cmd := exec.Command(
		"/bbin/sshd",
		"--ip", "[::0]",
		"--port", "22",
		"--privatekey", "/config/ssh_host_ecdsa_key",
		"--keys", "/config/authorized_keys")
	cmd.Env = environ
	cmd.Stdin = nil
	cmd.Stderr = os.Stderr
	cmd.Stdout = os.Stdout
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("startSsh: %v", err)
	}
	return nil
}

func acquireTime(rs []ttime.RoughtimeServer, ntps []ttime.NtpServer) {
	var tt time.Time
	for {
		t, err := ttime.AcquireTime(rs, ntps)
		if err != nil {
			log.Printf("Failed to acquire trusted time: %v", err)
			delay := timeRetry.Duration()
			log.Printf("Waiting %v before retrying time acquisition", delay)
			time.Sleep(delay)
			continue
		} else {
			tt = *t
			break
		}
	}
	timeRetry.Reset()

	log.Printf("Got trusted time: %v", tt)
	tv := unix.NsecToTimeval(tt.UnixNano())
	if err := unix.Settimeofday(&tv); err != nil {
		log.Printf("Unable to set system time: %v", err)
		return
	}
}

func seedRandomGenerator() {
	b := make([]byte, 8)
	_, err := crand.Read(b)
	if err != nil {
		log.Fatalf("Unable to read random seed, cannot safely continue: %v", err)
	}
	buf := bytes.NewReader(b)
	var seed int64
	if err := binary.Read(buf, NativeEndian(), &seed); err != nil {
		log.Fatalf("Unable to convert random seed, cannot safely continue: %v", err)
	}
	rand.Seed(seed)
}

func backgroundTimeSync(rs []ttime.RoughtimeServer, ntps []ttime.NtpServer) {
	for {
		delay := timeRefresh.Duration()
		log.Printf("Scheduling time re-sync in %s", delay.String())
		tmr := time.NewTimer(delay)
		<-tmr.C
		log.Printf("Re-syncing trusted time")
		acquireTime(rs, ntps)
	}
}

func loadSysconf(path string) *pb.SystemConfig {
	f, err := ioutil.ReadFile(path)
	if err != nil {
		log.Printf("Failed to read system configuration %s: %v", path, err)
		log.Printf("Using default system configuration")
		f = []byte{}
	}

	sysconf := &pb.SystemConfig{}
	if err := proto.UnmarshalText(string(f), sysconf); err != nil {
		log.Printf("Failed to unmarshal system configuration: %v", err)
		log.Printf("Using default system configuration")
	}

	return sysconf
}

func Startup(p Platform) (error, chan error) {
	return StartupWithConfig(p, config.DefaultConfig)
}

func StartupWithConfig(p Platform, c *config.Config) (error, chan error) {
	fmt.Printf("\n")
	fmt.Printf(banner)
	fmt.Printf("Welcome to u-bmc version %s\n\n", c.Version.Version)
	systemVersion.With(prometheus.Labels{"version": c.Version.Version}).Inc()

	// Seed the non-crypto random generator using the crypto one (which is
	// hardware based). The non-crypto generator is used for random back-off
	// timers and such, while the crypto one is used for crypto keys.
	seedRandomGenerator()

	loggers := []io.Writer{os.Stdout}
	lf, err := os.OpenFile("/tmp/u-bmc.log", os.O_RDWR|os.O_CREATE, 0600)
	if err != nil {
		log.Printf("os.OpenFile u-bmc.log: %v", err)
	} else {
		loggers = append(loggers, lf)
		log.SetOutput(io.MultiWriter(loggers...))
	}

	log.Printf("Initialize system hardware")
	if err := p.InitializeSystem(); err != nil {
		log.Printf("platform.InitializeSystem: %v", err)
		return err, nil
	}

	log.Printf("Starting GPIO drivers")
	gpio, err := startGpio(p)
	if err != nil {
		log.Printf("startGpio failed: %v", err)
		return err, nil
	}

	log.Printf("Starting fan system")
	fan, err := startFan(p)
	if err != nil {
		log.Printf("startFan failed: %v", err)
		return err, nil
	}

	tty, baud := p.HostUart()
	log.Printf("Configuring host UART console %s @ %d baud", tty, baud)
	uart, err := startUart(tty, baud)
	if err != nil {
		log.Printf("startUart failed: %v", err)
		return err, nil
	}

	log.Printf("Loading system configuration")
	sysconf := loadSysconf("/config/system.textpb")

	network, err := startNetwork(sysconf.Network)
	if err != nil {
		log.Printf("startNetwork failed: %v", err)
		return err, nil
	}

	// At this time we can assume having a hostname and network connectivity

	timeAcquired := make(chan bool)
	go func() {
		log.Printf("Acquiring trusted time")
		if time.Now().Year() > 2018 {
			// Consider the RTC trusted.
			// This means that if the RTC is set, don't block waiting getting trusted
			// time. If we do get a new trusted time however, make sure to update RTC.
			timeAcquired <- true
			acquireTime(c.RoughtimeServers, c.NtpServers)
		} else {
			acquireTime(c.RoughtimeServers, c.NtpServers)
			timeAcquired <- true
		}
		r, err := rtc.OpenRTC()
		if err != nil {
			log.Printf("Failed to open RTC: %v", err)
			return
		}
		tu := time.Now().UTC()
		if err := r.Set(tu); err != nil {
			log.Printf("Failed to update RTC: %v", err)
		}
	}()

	createFile("/etc/passwd", 0644, []byte("root:x:0:0:root:/root:/bbin/elvish"))
	createFile("/etc/group", 0644, []byte("root:x:0:"))

	// The platform libraries need access to physical memory
	unix.Mknod("/dev/mem", unix.S_IFCHR|0600, 0x0101)

	if c.StartDebugSshServer {
		log.Printf("Starting debug SSH server")
		// Make sure sshd starts up completely before we continue, to allow for debugging
		if err := startSsh(c.DebugSshServerKeys); err != nil {
			log.Printf("ssh server failed: %v", err)
		}
	}

	log.Printf("Starting OpenMetrics interface")
	if err := startMetrics(); err != nil {
		log.Printf("startMetrics failed: %v", err)
		return err, nil
	}

	log.Printf("Starting gRPC interface")
	rpc, err := startGRPC(gpio, fan, uart, &c.Version)
	if err != nil {
		log.Printf("startGRPC failed: %v", err)
		return err, nil
	}

	log.Printf("Starting DNS interface")
	dns, err := startDNS(network.FQDN(), network)
	if err != nil {
		log.Printf("startDNS failed: %v", err)
		return err, nil
	}

	akey, err := cert.LoadOrGenerateKey("/config/acme.key")
	if err != nil {
		log.Printf("Failed to load ACME key: %v", err)
		return err, nil
	}

	cm := &cert.Manager{
		FQDN:         network.FQDN(),
		AccountKey:   akey,
		ACMEConfig:   &c.ACME,
		ACMEHandlers: []cert.ACMEHandler{dns},
	}

	// The rest of the startup depends on the system having the correct time,
	// so initialize the rest in the background
	startupResult := make(chan error)
	go func() {
		if err := asyncStartup(p, c, rpc, cm, timeAcquired); err != nil {
			startupResult <- err
			return
		}
		startupResult <- nil
	}()

	return nil, startupResult
}

func asyncStartup(p Platform, c *config.Config, rpc RPCServer, cm *cert.Manager, t chan bool) error {
	// Before we enable remote calls, make sure we have acquired accurate time
	<-t
	systemHasTime.Set(1)

	// Start background time sync
	go backgroundTimeSync(c.RoughtimeServers, c.NtpServers)

	log.Printf("Time has been verified, loading system certificate")
	domain := cm.FQDN
	cf := fmt.Sprintf("/config/%s.crt", domain)
	kf := fmt.Sprintf("/config/%s.key", domain)

	var kp *tls.Certificate
	for {
		skp, err := tls.LoadX509KeyPair(cf, kf)
		if err != nil {
			if !os.IsNotExist(err) {
				log.Printf("tls.LoadX509KeyPair failed: %v", err)
			}
		}

		kp, err = cm.MaybeRenew(&skp)
		if err == nil {
			break
		}
		log.Printf("cert.Load failed: %v", err)
		delay := certRetry.Duration()
		log.Printf("Waiting %v before retrying certificate acquisition", delay)
		time.Sleep(delay)
	}
	certRetry.Reset()

	// Fail soft on failing to write these files. We can still serve from memory
	// and next reboot we will have to renew instead.
	if err := cert.SaveKeyPair(kp, cf, kf); err != nil {
		log.Printf("WARNING: System will use certificate from memory, but will have to renew it on reboot. Error was: %v", err)
	}

	log.Printf("Certificate available, enabling remote RPCs")
	if err := rpc.EnableRemote(kp); err != nil {
		log.Printf("rpc.EnableRemote failed: %v", err)
		return err
	}

	return nil
}

func Shell() {
	cmd := exec.Command("/bbin/login")
	cmd.Dir = "/"
	cmd.Env = environ
	cmd.Stdin = os.Stdin
	cmd.Stderr = os.Stderr
	cmd.Stdout = os.Stdout
	exited := make(chan bool)
	// Forward intr to the shell
	go intrHandler(cmd, exited)
	if err := cmd.Run(); err != nil {
		log.Printf("Failed to execute: %v", err)
	}
	exited <- true
}

func Reboot() {
	if err := unix.Reboot(unix.LINUX_REBOOT_CMD_RESTART); err != nil {
		log.Fatalf("reboot failed: %v", err)
	}
}
